version: "3.9"

services:

  app:
    build: .
    container_name: jadwal_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8001
    networks:
      - eai-network  

  db:
    image: postgres:15
    container_name: jadwal_db
    restart: always
    environment:
      POSTGRES_DB: jadwal_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - jadwal_data:/var/lib/postgresql/data
    networks:
      - eai-network    

  # queue:
  #   build: .
  #   container_name: jadwal_queue
  #   working_dir: /var/www
  #   volumes:
  #     - .:/var/www
  #   depends_on:
  #     - db
  #   command: php artisan queue:work

volumes:
  jadwal_data:

networks:
  eai-network:
    external: true
